from typing import List, Optional, Tuple
class AntiCheatInfo:
    __slots__ = ("name", "services", "processes", "drivers", "folders", "registry", "companies", "products")
    def __init__(
        self,
        name: str,
        *,
        services: Optional[List[str]] = None,
        processes: Optional[List[str]] = None,
        drivers: Optional[List[str]] = None,
        folders: Optional[List[str]] = None,
        registry: Optional[List[Tuple[str, str]]] = None,
        companies: Optional[List[str]] = None,
        products: Optional[List[str]] = None,
    ):
        self.name = name
        self.services = services if services is not None else []
        self.processes = processes if processes is not None else []
        self.drivers = drivers if drivers is not None else []
        self.folders = folders if folders is not None else []
        self.registry = registry if registry is not None else []
        self.companies = companies if companies is not None else []
        self.products = products if products is not None else []
def get_ac_database() -> List[AntiCheatInfo]:
    return [
        AntiCheatInfo(
            "ACE (AnticheatExpert)",
            services=["ACE", "ACEDRV", "ACEService", "AntiCheatExpert", "ACE-BASE", "SGuard", "sgameguard", "TPHelper", "ACEClient", "UniRTCX", "SGuardSvc", "TesSafe", "TenSafe", "TP2Helper", "ACELoader", "ACE-Service32", "ACE-Service64"],
            processes=["ACE.exe", "ACEDRV.exe", "ACEService.exe", "AntiCheatExpert.exe", "ACE-BASE.exe", "SGuard64.exe", "SGuard32.exe", "ACELoader.exe", "TPHelper.exe", "TenSafe.exe", "TenSafe_1.exe", "TP2Helper.exe", "UniRTCX.exe", "ACE-Service64.exe", "ACE-Service32.exe", "SGuardSvc.exe", "ACE-Guard.exe", "TesSafe.exe"],
            drivers=["ACE-Base.sys", "ACEDRV.sys", "ACE.sys", "ACE-Guard.sys", "SGuard64.sys", "AntiCheatExpert.sys", "TesSafe.sys", "TenSafe.sys", "UniRTCX.sys", "ACELoader.sys", "TP2Helper.sys", "SGuard32.sys"],
            folders=[
                "ACE", "AntiCheatExpert", "Tencent\\ACE", "Tencent\\AntiCheatExpert",
                "Tencent\\TPHelper", "Tencent\\TenSafe", "UniRTCX",
                "AppData\\Local\\ACE", "AppData\\Local\\AntiCheatExpert",
                "AppData\\Roaming\\Tencent\\ACE", "AppData\\Roaming\\AntiCheatExpert",
                "AppData\\LocalLow\\Tencent",
                "ProgramData\\ACE", "ProgramData\\AntiCheatExpert",
                "ProgramData\\Tencent\\ACE", "ProgramData\\Tencent\\AntiCheatExpert",
                "Temp\\ACE", "Windows\\Temp\\ACE",
                "Common Files\\Tencent",
                "Program Files\\AntiCheatExpert", "Program Files (x86)\\AntiCheatExpert",
            ],
            registry=[
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\ACE"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\ACE"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\ACEDRV"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\ACE-BASE"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\SGuard"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\AntiCheatExpert"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\UniRTCX"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Tencent\ACE"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\AntiCheatExpert"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\Tencent"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\Tencent\ACE"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Tencent\ACE\Core"),
                ("HKEY_CURRENT_USER", r"Software\Tencent\ACE"),
                ("HKEY_CURRENT_USER", r"Software\AntiCheatExpert"),
            ],
            companies=["Tencent", "AntiCheatExpert", "Tencent Technology", "Tencent Technology (Shenzhen) Company Limited"],
            products=["ACE", "AntiCheatExpert", "Anti Cheat Expert", "Tencent Anti-Cheat", "SGuard", "UniRTCX"],
        ),

        AntiCheatInfo(
            "EA Javelin",
            services=[
                "EAAntiCheat", "EAAntiCheatService", "Javelin", "JavService", "EAC",
                "EAAntiCheat.GameServiceV1", "EAAntiCheat.GlobalServiceV1",
                "EABackgroundService", "EADesktop", "EALocalHostSvc",
                "Origin Client Service", "OriginWebHelperService",
            ],
            processes=[
                "EAAntiCheat.GameService.exe", "EAAntiCheat.Installer.exe", "EAAntiCheat.exe",
                "EAAntiCheat.GameServiceV1.exe",
                "Javelin.exe", "JavCS.exe",
                "bf2042.exe", "BFV.exe",
                "EADesktop.exe", "EABackgroundService.exe",
                "EAConnect_microsoft.exe", "EALauncher.exe",
                "Origin.exe", "OriginWebHelperService.exe",
                "EALocalHostSvc.exe", "EAUpdate.exe",
                "EAUpdater.exe", "EAHelp.exe",
            ],
            drivers=["EAAntiCheat.sys", "EAAntiCheatService.sys", "Javelin.sys", "JavelinAntiCheat.sys", "Jav.sys", "EAC.sys", "EAAntiCheat_EOS.sys"],
            folders=[
                "EAAntiCheat", "EA Anti-Cheat", "Electronic Arts\\EAAntiCheat",
                "Javelin", "JavelinAntiCheat",
                "Electronic Arts\\EA Desktop",
                "Electronic Arts\\Origin",
                "ProgramData\\Electronic Arts",
                "ProgramData\\Electronic Arts\\EA Desktop",
                "ProgramData\\EA\\AC",
                "ProgramData\\eaanticheat\\Crashdumps",
                "ProgramData\\Origin",
                "ProgramData\\EA Desktop",
                "Program Files\\EA\\AC",
                "AppData\\Local\\Electronic Arts", "AppData\\Local\\Origin",
                "AppData\\Local\\EA Desktop", "AppData\\Local\\EADesktop",
                "AppData\\Roaming\\Electronic Arts",
                "AppData\\Roaming\\Origin",
                "AppData\\Roaming\\EA Desktop",
                "Temp\\Electronic Arts", "Windows\\Temp\\EA",
                "Common Files\\Electronic Arts",
            ],
            registry=[
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EAAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EAAntiCheat.GameServiceV1"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EAAntiCheat.GlobalServiceV1"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EAAntiCheatService"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\Javelin"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EABackgroundService"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Electronic Arts"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Electronic Arts\EA Desktop"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Electronic Arts\EAAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\EA Anti-Cheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\Origin"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\Electronic Arts"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\Electronic Arts\EA Desktop"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\EA Anti-Cheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\Origin"),
                ("HKEY_CURRENT_USER", r"Software\Electronic Arts"),
                ("HKEY_CURRENT_USER", r"Software\Electronic Arts\EA Desktop"),
                ("HKEY_CURRENT_USER", r"Software\EA Anti-Cheat"),
                ("HKEY_CURRENT_USER", r"Software\Origin"),
            ],
            companies=["Electronic Arts", "Electronic Arts Inc.", "EA Digital Illusions CE AB", "EA Swiss Sarl"],
            products=["EA Anti-Cheat", "EAAntiCheat", "Javelin", "EA Desktop", "Origin", "EA Anti-Cheat Service", "EA App"],
        ),
        AntiCheatInfo(
            "EAC (EasyAntiCheat)",
            services=[
                "EasyAntiCheat", "EasyAntiCheat_EOS", "EasyAntiCheat_EOS_Service",
                "EasyAntiCheat_SOS", "EasyAntiCheatSetup",
                "EasyAntiCheat_EOSLauncher", "EasyAntiCheat_EOSLauncherService",
            ],
            processes=[
                "EasyAntiCheat.exe", "EasyAntiCheat_EOS.exe", "EasyAntiCheat_SOS.exe",
                "EasyAntiCheat_Setup.exe", "EasyAntiCheat_Launcher.exe",
                "start_protected_game.exe",
                "EasyAntiCheat_x64.exe", "EasyAntiCheat_x86.exe",
                "EasyAntiCheat_EOS_Setup.exe", "EasyAntiCheat_Service.exe",
                "EasyAntiCheat_Service_x64.exe", "EasyAntiCheat_Service_x86.exe",
            ],
            drivers=["EasyAntiCheat.sys", "EasyAntiCheat_EOS.sys", "EasyAntiCheat_SOS.sys", "EasyAntiCheat_EOSA.sys"],
            folders=[
                "EasyAntiCheat", "EasyAntiCheat_EOS", "EasyAntiCheat_SOS",
                "EasyAntiCheat\\Certificates", "EasyAntiCheat_EOS\\Certificates",
                "Epic Games\\EasyAntiCheat", "Epic Games\\EasyAntiCheat_EOS",
                "Steam\\EasyAntiCheat",
                "Program Files\\EasyAntiCheat",
                "Program Files (x86)\\EasyAntiCheat",
                "Program Files (x86)\\EasyAntiCheat_EOS",
                "Common Files\\EasyAntiCheat",
                "ProgramData\\EasyAntiCheat",
                "ProgramData\\EasyAntiCheat_EOS",
                "Program Files (x86)\\EasyAntiCheat_EOS\\Logs",
                "AppData\\Local\\EasyAntiCheat",
                "AppData\\Roaming\\EasyAntiCheat",
                "steamapps\\common\\EasyAntiCheat",
                "steamapps\\common\\EasyAntiCheat_EOS",
                "Temp\\EasyAntiCheat", "Windows\\Temp\\EasyAntiCheat",
            ],
            registry=[
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EasyAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EasyAntiCheat_EOS"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EasyAntiCheat_SOS"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\EasyAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\EasyAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\EpicGames\EasyAntiCheat"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\EpicGames\EasyAntiCheat\Logs"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\EasyAntiCheat_EOS\Parameters"),
                ("HKEY_CURRENT_USER", r"Software\EasyAntiCheat"),
                ("HKEY_CURRENT_USER", r"Software\Epic Games\EasyAntiCheat"),
            ],
            companies=["EasyAntiCheat", "Epic Games", "Kamu", "EasyAntiCheat Oy", "Epic Games, Inc.", "Epic Games AB"],
            products=["EasyAntiCheat", "Easy Anti-Cheat", "EasyAntiCheat Service", "Easy Anti-Cheat Service", "EasyAntiCheat_EOS"],
        ),
        AntiCheatInfo(
            "BE (BattlEye)",
            services=[
                "BEService", "BattlEye", "BEServer", "BEClient", "BattlEyeService", "BEDaisy",
                "BEService_arma3", "BEService_pubg", "BEService_r5apex",
                "BEService_dayz", "BEService_unturned",
            ],
            processes=[
                "BEService.exe", "BattlEye.exe", "BEClient.exe",
                "BEServer_x64.exe", "BEServer_x86.exe",
                "BEService_x64.exe", "BEService_x86.exe",
                "BattlEye_Update.exe", "BattlEye_Install.exe",
                "BEClient_x64.exe", "BEClient_x86.exe",
                "BattlEyeLauncher.exe", "BattlEyeService.exe",
            ],
            drivers=["BEDaisy.sys", "BattlEye.sys", "BE.sys", "bedaisy.sys", "battleye_x64.sys", "battleye_x86.sys"],
            folders=[
                "BattlEye", "BEService",
                "Program Files (x86)\\Common Files\\BattlEye",
                "Program Files\\Common Files\\BattlEye",
                "Common Files\\BattlEye",
                "Common Files\\BattlEye\\BEService",
                "Common Files\\BattlEye\\Logs",
                "ProgramData\\BattlEye",
                "ProgramData\\BattlEye\\BEService",
                "AppData\\Local\\BattlEye",
                "AppData\\Roaming\\BattlEye",
                "BattlEye\\BEService",
                "Temp\\BattlEye", "Temp\\BEService",
                "Windows\\Temp\\BattlEye",
            ],
            registry=[
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\BEService"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\BattlEye"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\BEDaisy"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\BattlEye"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\BEDaisy\Parameters"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\BattlEye"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\BattlEye\BEService"),
                ("HKEY_CURRENT_USER", r"Software\BattlEye"),
            ],
            companies=["BattlEye Innovations e.K.", "BattlEye Innovations", "BattlEye GmbH", "BattlEye Innovations e.K"],
            products=["BattlEye", "BattlEye Anti-Cheat", "BattlEye Service", "BEService", "BEDaisy"],
        ),
        AntiCheatInfo(
            "HoYoProtect",
            services=["mhyprot2", "mhyprot3", "HoYoProtect", "mhyprot", "GenshinImpact", "mhypbase", "HoYoKProtect", "UniRTC", "HoYoBase", "mhyprot1", "mhyprot2_3"],
            processes=[
                "GenshinImpact.exe", "YuanShen.exe",
                "Honkai Star Rail.exe", "StarRail.exe",
                "ZenlessZoneZero.exe",
                "HoYoProtect.exe", "mhyprot2.sys", "mhyprot3.sys",
                "HYPLauncher.exe", "HoYoPlay.exe", "HoYoBase.exe",
                "HoYoShield.exe", "HoYoKProtect.exe",
            ],
            drivers=["mhyprot2.sys", "mhyprot3.sys", "HoYoProtect.sys", "mhyprot.sys", "mhypbase.sys", "HoYoKProtect.sys", "mhyprot2_3.sys", "mhyprot1.sys", "HoYoShield.sys"],
            folders=[
                "Genshin Impact", "Genshin Impact Game", "YuanShen",
                "Honkai Star Rail", "Honkai Star Rail Game",
                "ZenlessZoneZero", "ZenlessZoneZero Game",
                "miHoYo", "HoYoverse",
                "miHoYo\\Genshin Impact", "HoYoverse\\Genshin Impact",
                "miHoYo\\Honkai Star Rail", "HoYoverse\\Honkai Star Rail",
                "miHoYo\\ZenlessZoneZero", "HoYoverse\\ZenlessZoneZero",
                "ProgramData\\miHoYo", "ProgramData\\HoYoverse",
                "ProgramData\\miHoYo\\Genshin Impact", "ProgramData\\HoYoverse\\Genshin Impact",
                "ProgramData\\miHoYo\\Genshin Impact\\CrashReports",
                "ProgramData\\HoYoverse\\CrashReports",
                "AppData\\Local\\Temp\\mhyprot",
                "AppData\\LocalLow\\miHoYo", "AppData\\LocalLow\\HoYoverse",
                "AppData\\LocalLow\\miHoYo\\Genshin Impact",
                "AppData\\LocalLow\\miHoYo\\Honkai Star Rail",
                "AppData\\LocalLow\\miHoYo\\ZenlessZoneZero",
                "AppData\\Local\\miHoYo", "AppData\\Local\\HoYoverse",
                "AppData\\Local\\HoYoPlay",
                "AppData\\Roaming\\miHoYo", "AppData\\Roaming\\HoYoverse",
                "Temp\\miHoYo", "Windows\\Temp\\miHoYo",
                "Common Files\\miHoYo",
            ],
            registry=[
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\miHoYo"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\HoYoverse"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\mhyprot"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\mhyprot2"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\mhyprot3"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\HoYoProtect"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\mhypbase"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\HoYoKProtect"),
                ("HKEY_LOCAL_MACHINE", r"SYSTEM\CurrentControlSet\Services\HoYoShield"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\miHoYo"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\miHoYo\Genshin Impact"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\WOW6432Node\HoYoverse"),
                ("HKEY_LOCAL_MACHINE", r"SOFTWARE\miHoYo\Genshin Impact\Settings"),
                ("HKEY_CURRENT_USER", r"Software\miHoYo"),
                ("HKEY_CURRENT_USER", r"Software\HoYoverse"),
                ("HKEY_CURRENT_USER", r"Software\miHoYo\Genshin Impact"),
                ("HKEY_CURRENT_USER", r"Software\HoYoverse\Genshin Impact"),
            ],
            companies=["miHoYo Co.,Ltd.", "COGNOSPHERE PTE. LTD.", "Cognosphere", "miHoYo", "HoYoverse", "Shanghai miHoYo"],
            products=["Genshin Impact", "Honkai Star Rail", "Zenless Zone Zero", "HoYoPlay", "mhyprot", "HoYoProtect", "HoYoBase", "HoYoShield"],
        ),
    ]
